<a href="https://colab.research.google.com/github/wyjun1988/dataScience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [ ]:
ar = np.array([0,1,2])

In [ ]:
ar

array([0, 1, 2])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
data = [0, 1, 2, 3]
x= np.array(data)
print(2*x)
x = list(map(lambda x:2*x, data))
print(x)

[0 2 4 6]
[0, 2, 4, 6]


## 2D array

In [ ]:
c = np.array([[0,1,2],[3,4,5]]) # 2x3 array
len(c)
len(c[0])

3

## 3D array


In [ ]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [ ]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [ ]:
print(d.ndim)

3


In [ ]:
print(d.shape)

(2, 3, 4)


In [ ]:
d[0,1,2]

7

In [ ]:
d[0,1,:]

array([5, 6, 7, 8])

In [ ]:
d[:,1,2]

array([ 7, 17])

In [3]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [4]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [7]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [8]:
x = np.array([1,2,3])

# data type

In [9]:
x.dtype

dtype('int64')

In [10]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [11]:
x

array([1., 2., 3.], dtype=float32)

In [12]:
x = np.array([1,2,3], dtype='U')

In [13]:
x[0]+x[1]

'12'

# 배열 생성

In [18]:
a = np.zeros((5,3), dtype='f')

In [19]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [20]:
f = np.ones_like(a, dtype='f')

In [21]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [22]:
g = np.empty((4,3))

In [23]:
g

array([[4.12328058e-316, 0.00000000e+000, 8.06809200e-321],
       [4.12429519e-316, 6.93454253e-310, 6.93454253e-310],
       [6.93454253e-310, 6.93454253e-310, 4.12327583e-316],
       [4.94065646e-324, 2.12199579e-314, 4.44659081e-323]])

In [24]:
g = np.empty(a.shape)

In [25]:
g

array([[ 3.63393267e-316,  1.06099790e-312,  1.01855798e-312],
       [ 9.54898106e-313,  1.14587773e-312,  1.01855798e-312],
       [ 1.23075756e-312,  1.03977794e-312,  1.10343781e-312],
       [ 9.76118064e-313,  1.14587773e-312,  1.10343781e-312],
       [ 1.12465777e-312,  3.44981226e+175, -2.53481361e-170]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [30]:
g.T

array([[ 3.63393267e-316,  9.54898106e-313,  1.23075756e-312,
         9.76118064e-313,  1.12465777e-312],
       [ 1.06099790e-312,  1.14587773e-312,  1.03977794e-312,
         1.14587773e-312,  3.44981226e+175],
       [ 1.01855798e-312,  1.01855798e-312,  1.10343781e-312,
         1.10343781e-312, -2.53481361e-170]])

# 배열의 크기 변경

In [31]:
g. reshape(3,5)
g

array([[ 3.63393267e-316,  1.06099790e-312,  1.01855798e-312],
       [ 9.54898106e-313,  1.14587773e-312,  1.01855798e-312],
       [ 1.23075756e-312,  1.03977794e-312,  1.10343781e-312],
       [ 9.76118064e-313,  1.14587773e-312,  1.10343781e-312],
       [ 1.12465777e-312,  3.44981226e+175, -2.53481361e-170]])

In [33]:
g.flatten()

array([ 3.63393267e-316,  1.06099790e-312,  1.01855798e-312,
        9.54898106e-313,  1.14587773e-312,  1.01855798e-312,
        1.23075756e-312,  1.03977794e-312,  1.10343781e-312,
        9.76118064e-313,  1.14587773e-312,  1.10343781e-312,
        1.12465777e-312,  3.44981226e+175, -2.53481361e-170])

In [37]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [38]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# concatenate

In [39]:
a1 = np.ones((2,3))

In [40]:
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
a2 = np.zeros((2,2))

In [43]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [44]:
a2 = np.zeros((1,3))
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [45]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
d = np.dstack([c1,c2])
d
d.shape

(3, 4, 2)

In [51]:
c = np.stack([c1, c2])
c.shape

(2, 3, 4)

In [52]:
c = np.stack([c1, c2], axis=1)
c.shape

(3, 2, 4)

In [55]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [56]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

# Grid point

In [57]:
x = np.arange(3)
y = np.arange(5)

X, Y = np.meshgrid(x,y)
print(X)
print(Y)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [59]:
[list(zip(x,y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

# Vectorized operation

In [60]:
a = np.array([1,2,3,4])
b = np.array([4,2,3,1])
a == b

array([False,  True,  True, False])

In [61]:
a >= b

array([False,  True,  True,  True])

In [62]:
c = np.array([1,2,3,4])
np.all(a==b)

False

In [63]:
np.all(a==c)

True

In [64]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## broadcasting

In [10]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])

In [11]:
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [18]:
[range(10)[i:i+3] for i in range(5)]

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]