<a href="https://colab.research.google.com/github/wyjun1988/dataScience/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Tensor
https://tutorials.pytorch.kr/beginner/basics/tensorqs_tutorial.html
위 사이트의 내용을 요약 발췌
\
내용 정리:\
https://lofty-litter-31d.notion.site/Tensor-896366566ba64e07a2b6cc1685fc8c02

## Tensor initialization

In [2]:
# from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [7]:
# from numpy
np_array=np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
# from tensor
x_ones=torch.ones_like(x_data)
x_rand=torch.rand_like(x_data, dtype=torch.float)


## prebuilt initalization

In [9]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

## GPU 사용

In [ ]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

## Tensor 연산
### indexing sliceing

In [11]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"last column: {tensor[...,-1]}")
# set last column 0
tensor[:,-1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


### concatenate

In [13]:
# dim: the dimension over which the tensors are concatenated
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0) 
print(t2)

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


## 산술연산

In [14]:
# multiplication
y1 = tensor @ tensor.T # T: transpose
y2 = tensor.matmul(tensor.T)
y3=torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

#element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3=torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

# sum
agg = tensor.sum()
print(agg)
agg_item = agg.item() # get python value
print(agg_item, type(agg_item))


tensor(12.)
12.0 <class 'float'>


## in-place 연산
연산 결과를 피연산자에 저장하는 연산. _접미사를 자는다. 예를들어 x.copy_(y)는 x를 변경한다.

In [18]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.]])


## Split

In [21]:
x = torch.arange(8)
print(x)
sp_x = torch.tensor_split(x, 3)
print(sp_x)
x = torch.arange(14).reshape(2, 7)
sp_x=torch.tensor_split(x, (1, 6), dim=1)
print(sp_x)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7]))
(tensor([[0],
        [7]]), tensor([[ 1,  2,  3,  4,  5],
        [ 8,  9, 10, 11, 12]]), tensor([[ 6],
        [13]]))
